services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production  
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/src
    command: python main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/tests
    command: pytest -v