services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production  
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/src
    command: python main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/tests
    command: pytest -v

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/
    command: tail -f /dev/null  # Keeps container alive
    stdin_open: true
    tty: true