services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production  
    volumes:
      - .:/app:z
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/src
    command: python main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app:z
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/tests
    command: pytest -v

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app:z
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/
    command: tail -f /dev/null  # Keeps container alive
    stdin_open: true
    tty: true

  api:
      build:
        context: .
        dockerfile: Dockerfile
        target: api
      ports:
        - "8000:8000"
      volumes:
        - .:/app:z
      environment:
        - PYTHONPATH=/app/src
      working_dir: /app/
      command: uvicorn serverhelper:app --host 0.0.0.0 --port 8000
      stdin_open: true
      tty: true